window.ADVENTURER_FEATURE_DESCRIPTIONS = {
  "Action Surge": "Push beyond normal limits for an extra burst of action in combat.",
  "Arcane Recovery": "Recover a portion of spent magical power during a short rest.",
  "Arcane Tradition": "Choose the wizard tradition that shapes your advanced magical study.",
  "Archetype Feature": "Gain a feature from the subclass tied to this class.",
  "Archdruid": "Reach the peak of druidic endurance and transformation.",
  "Aura Improvements": "Expand and strengthen the reach of your paladin auras.",
  "Aura of Courage": "Bolster nearby allies against fear.",
  "Aura of Protection": "Support nearby allies with your force of will.",
  "Bard College": "Choose the bardic college that defines your performance, magic, and style.",
  "Bardic Inspiration": "Grant an ally a die they can use to improve an important roll.",
  "Beast Spells": "Keep spellcasting options available while transformed.",
  "Blindsense": "Notice hidden or unseen creatures at close range.",
  "Brutal Critical": "Make weapon critical hits more punishing.",
  "Channel Divinity": "Expend divine power for cleric or oath-specific effects.",
  "Cleansing Touch": "End harmful magical effects through divine power.",
  "College Feature": "Gain a feature from your chosen bard college.",
  "Countercharm": "Use performance to help allies resist charm and fear.",
  "Cunning Action": "Move, hide, or disengage quickly during combat.",
  "Danger Sense": "React instinctively to dangerous effects you can perceive.",
  "Deflect Missiles": "Reduce or redirect incoming ranged weapon damage.",
  "Diamond Soul": "Harden your body and spirit against many dangers.",
  "Divine Domain": "Choose the cleric domain that defines your divine calling.",
  "Divine Health": "Become protected from disease through sacred power.",
  "Divine Intervention": "Call for direct aid from your deity in desperate moments.",
  "Divine Intervention Improvement": "Your divine intervention becomes more reliable.",
  "Divine Order": "Choose whether your cleric leans toward martial protection or deeper divine magic.",
  "Divine Sense": "Sense powerful celestial, fiendish, or undead presences nearby.",
  "Divine Smite": "Turn spell power into extra radiant weapon damage.",
  "Destroy Undead": "Make your Turn Undead effects more decisive against weaker undead.",
  "Domain Feature": "Gain a feature from your chosen divine domain.",
  "Druid Circle": "Choose the druid circle that shapes your nature magic.",
  "Circle Feature": "Gain a feature from your chosen druid circle.",
  "Druidic": "Know the secret language and signs of druids.",
  "Eldritch Invocations": "Customize your warlock magic with occult gifts and tricks.",
  "Eldritch Master": "Restore warlock magic through a focused occult rite.",
  "Elusive": "Become extremely difficult to pin down or exploit in combat.",
  "Empty Body": "Use ki to become harder to perceive and harm.",
  "Evasion": "Avoid or reduce damage from many area effects.",
  "Expertise": "Double proficiency for chosen skills or tools.",
  "Extra Attack": "Attack more than once when taking the Attack action.",
  "Fast Movement": "Increase your movement speed while unburdened.",
  "Favored Enemy": "Mark or study chosen foes to improve tracking and combat pressure.",
  "Feral Instinct": "React faster when combat begins and avoid being caught flat-footed.",
  "Feral Senses": "Fight more effectively against creatures you cannot clearly see.",
  "Fighting Style": "Choose a combat style that improves a weapon or defense specialty.",
  "Foe Slayer": "Strike favored enemies with exceptional accuracy or force.",
  "Font of Inspiration": "Recover bardic inspiration more often.",
  "Font of Magic": "Use sorcery points to fuel flexible spellcasting.",
  "Hide in Plain Sight": "Use preparation and terrain to become very difficult to spot.",
  "Improved Divine Smite": "Add steady radiant force to your melee weapon hits.",
  "Indomitable": "Reroll a failed saving throw in a critical moment.",
  "Indomitable Might": "Rely on raw strength when a Strength check would come up short.",
  "Jack of All Trades": "Add part of your proficiency bonus to many non-proficient checks.",
  "Ki": "Use ki points to fuel monk techniques.",
  "Ki-Empowered Strikes": "Your monk strikes count as magically empowered for overcoming resistance.",
  "Land's Stride": "Move through difficult natural terrain more easily.",
  "Lay on Hands": "Draw from a healing pool to restore hit points or cure ailments.",
  "Magical Secrets": "Learn spells normally outside your bard spell list.",
  "Martial Archetype": "Choose the fighter archetype that defines your combat discipline.",
  "Martial Arts": "Use monk training to fight effectively without heavy weapons or armor.",
  "Metamagic": "Spend sorcery points to alter how your spells behave.",
  "Monastic Tradition": "Choose the monk tradition that shapes your ki techniques.",
  "Mystic Arcanum": "Gain a powerful warlock spell you can cast without using pact slots.",
  "Natural Explorer": "Gain benefits tied to wilderness travel and chosen terrain.",
  "Otherworldly Patron": "Choose the patron whose bargain fuels your warlock magic.",
  "Origin Feature": "Gain a feature from your sorcerous origin.",
  "Oath Feature": "Gain a feature from your sacred oath.",
  "Pact Boon": "Receive a pact gift that shapes how your warlock fights or casts.",
  "Pact Magic": "Cast warlock spells through pact slots that recover quickly.",
  "Patron Feature": "Gain a feature from your otherworldly patron.",
  "Path Feature": "Gain a feature from your barbarian path.",
  "Perfect Self": "Regain ki when you begin combat with none remaining.",
  "Persistent Rage": "Maintain rage more reliably.",
  "Primeval Awareness": "Sense certain creature types through ranger magic or focus.",
  "Primal Champion": "Raise your barbarian body beyond normal mortal limits.",
  "Primal Path": "Choose the barbarian path that shapes your rage.",
  "Purity of Body": "Become protected from disease and poison.",
  "Rage": "Enter a battle fury that improves durability and melee damage.",
  "Ranger Archetype": "Choose the ranger archetype that shapes your hunting style.",
  "Reckless Attack": "Trade defense for advantage on forceful melee attacks.",
  "Reliable Talent": "Turn many proficient skill checks into dependable results.",
  "Relentless Rage": "Fight on when damage would otherwise drop you.",
  "Roguish Archetype": "Choose the rogue archetype that defines your specialty.",
  "Sacred Oath": "Choose the paladin oath that defines your vows and powers.",
  "Second Wind": "Recover a small amount of hit points during combat.",
  "Signature Spells": "Prepare a small set of favorite spells for frequent use.",
  "Slippery Mind": "Strengthen your mental defenses.",
  "Slow Fall": "Reduce damage from falling.",
  "Sneak Attack": "Deal extra damage when you strike with advantage or an opening.",
  "Song of Rest": "Improve the healing allies regain during a short rest.",
  "Sorcerous Origin": "Choose the source that awakened your innate magic.",
  "Sorcerous Restoration": "Regain sorcery points when depleted.",
  "Spell Mastery": "Cast selected low-level wizard spells with exceptional ease.",
  "Spellcasting": "Gain this class's spellcasting progression and spell rules.",
  "Stroke of Luck": "Turn a failed attack or ability check into success.",
  "Stunning Strike": "Spend ki to try to stun a creature you hit.",
  "Superior Inspiration": "Regain bardic inspiration when entering combat without any.",
  "Thieves' Cant": "Know the coded language and signs used by rogues and criminals.",
  "Timeless Body": "Your body resists some effects of age and hardship.",
  "Tongue of the Sun and Moon": "Communicate across language barriers through monk training.",
  "Tradition Feature": "Gain a feature from your chosen tradition.",
  "Unarmored Defense": "Calculate AC from agility, endurance, or discipline instead of armor.",
  "Unarmored Movement": "Move faster while not wearing armor or using a shield.",
  "Uncanny Dodge": "Use your reaction to reduce damage from an attacker you can see.",
  "Vanish": "Hide quickly and avoid being tracked by mundane means.",
  "Wild Shape": "Use druidic power to assume beast forms or related class options."
};

window.ADVENTURER_CLASS_RULE_MEMORY = {
  barbarian: {
    label: "Barbarian",
    hitDie: 12,
    asiLevels: [4, 8, 12, 16, 19],
    subclassLevel: 3,
    subclassLabel: "Primal Path",
    levels: {
      1: ["Rage", "Unarmored Defense"],
      2: ["Reckless Attack", "Danger Sense"],
      3: ["Primal Path"],
      5: ["Extra Attack", "Fast Movement"],
      6: ["Path Feature"],
      7: ["Feral Instinct"],
      9: ["Brutal Critical"],
      10: ["Path Feature"],
      11: ["Relentless Rage"],
      13: ["Brutal Critical"],
      14: ["Path Feature"],
      15: ["Persistent Rage"],
      17: ["Brutal Critical"],
      18: ["Indomitable Might"],
      20: ["Primal Champion"]
    }
  },
  bard: {
    label: "Bard",
    hitDie: 8,
    asiLevels: [4, 8, 12, 16, 19],
    subclassLevel: 3,
    subclassLabel: "Bard College",
    levels: {
      1: ["Spellcasting", "Bardic Inspiration"],
      2: ["Jack of All Trades", "Song of Rest"],
      3: ["Bard College", "Expertise"],
      5: ["Font of Inspiration"],
      6: ["Countercharm", "College Feature"],
      10: ["Expertise", "Magical Secrets"],
      14: ["College Feature", "Magical Secrets"],
      18: ["Magical Secrets"],
      20: ["Superior Inspiration"]
    }
  },
  cleric: {
    label: "Cleric",
    hitDie: 8,
    asiLevels: [4, 8, 12, 16, 19],
    subclassLevel: 3,
    subclassLabel: "Divine Domain",
    choices: {
      1: [
        {
          key: "divineOrder",
          label: "Divine Order",
          options: [
            {
              value: "protector",
              label: "Protector",
              description: "Gain a more martial cleric direction, including heavier defensive training and weapon readiness."
            },
            {
              value: "thaumaturge",
              label: "Thaumaturge",
              description: "Lean further into divine magic, improving sacred knowledge and cantrip flexibility."
            }
          ]
        }
      ]
    },
    levels: {
      1: ["Spellcasting", "Divine Order"],
      2: ["Channel Divinity"],
      3: ["Divine Domain"],
      5: ["Destroy Undead"],
      6: ["Channel Divinity", "Domain Feature"],
      8: ["Destroy Undead", "Domain Feature"],
      10: ["Divine Intervention"],
      17: ["Destroy Undead", "Domain Feature"],
      20: ["Divine Intervention Improvement"]
    }
  },
  druid: {
    label: "Druid",
    hitDie: 8,
    asiLevels: [4, 8, 12, 16, 19],
    subclassLevel: 2,
    subclassLabel: "Druid Circle",
    levels: {
      1: ["Druidic", "Spellcasting"],
      2: ["Wild Shape", "Druid Circle"],
      6: ["Circle Feature"],
      10: ["Circle Feature"],
      14: ["Circle Feature"],
      18: ["Timeless Body", "Beast Spells"],
      20: ["Archdruid"]
    }
  },
  fighter: {
    label: "Fighter",
    hitDie: 10,
    asiLevels: [4, 6, 8, 12, 14, 16, 19],
    subclassLevel: 3,
    subclassLabel: "Martial Archetype",
    levels: {
      1: ["Fighting Style", "Second Wind"],
      2: ["Action Surge"],
      3: ["Martial Archetype"],
      5: ["Extra Attack"],
      7: ["Archetype Feature"],
      9: ["Indomitable"],
      10: ["Archetype Feature"],
      11: ["Extra Attack"],
      13: ["Indomitable"],
      15: ["Archetype Feature"],
      17: ["Action Surge", "Indomitable"],
      18: ["Archetype Feature"],
      20: ["Extra Attack"]
    }
  },
  monk: {
    label: "Monk",
    hitDie: 8,
    asiLevels: [4, 8, 12, 16, 19],
    subclassLevel: 3,
    subclassLabel: "Monastic Tradition",
    levels: {
      1: ["Unarmored Defense", "Martial Arts"],
      2: ["Ki", "Unarmored Movement"],
      3: ["Monastic Tradition", "Deflect Missiles"],
      4: ["Slow Fall"],
      5: ["Extra Attack", "Stunning Strike"],
      6: ["Ki-Empowered Strikes", "Tradition Feature"],
      7: ["Evasion", "Stillness of Mind"],
      10: ["Purity of Body"],
      11: ["Tradition Feature"],
      13: ["Tongue of the Sun and Moon"],
      14: ["Diamond Soul"],
      15: ["Timeless Body"],
      17: ["Tradition Feature"],
      18: ["Empty Body"],
      20: ["Perfect Self"]
    }
  },
  paladin: {
    label: "Paladin",
    hitDie: 10,
    asiLevels: [4, 8, 12, 16, 19],
    subclassLevel: 3,
    subclassLabel: "Sacred Oath",
    levels: {
      1: ["Divine Sense", "Lay on Hands"],
      2: ["Fighting Style", "Spellcasting", "Divine Smite"],
      3: ["Divine Health", "Sacred Oath"],
      5: ["Extra Attack"],
      6: ["Aura of Protection"],
      7: ["Oath Feature"],
      10: ["Aura of Courage"],
      11: ["Improved Divine Smite"],
      14: ["Cleansing Touch"],
      15: ["Oath Feature"],
      18: ["Aura Improvements"],
      20: ["Oath Feature"]
    }
  },
  ranger: {
    label: "Ranger",
    hitDie: 10,
    asiLevels: [4, 8, 12, 16, 19],
    subclassLevel: 3,
    subclassLabel: "Ranger Archetype",
    levels: {
      1: ["Favored Enemy", "Natural Explorer"],
      2: ["Fighting Style", "Spellcasting"],
      3: ["Ranger Archetype", "Primeval Awareness"],
      5: ["Extra Attack"],
      7: ["Archetype Feature"],
      8: ["Land's Stride"],
      10: ["Hide in Plain Sight"],
      11: ["Archetype Feature"],
      14: ["Vanish"],
      15: ["Archetype Feature"],
      18: ["Feral Senses"],
      20: ["Foe Slayer"]
    }
  },
  rogue: {
    label: "Rogue",
    hitDie: 8,
    asiLevels: [4, 8, 10, 12, 16, 19],
    subclassLevel: 3,
    subclassLabel: "Roguish Archetype",
    levels: {
      1: ["Expertise", "Sneak Attack", "Thieves' Cant"],
      2: ["Cunning Action"],
      3: ["Roguish Archetype"],
      5: ["Uncanny Dodge"],
      6: ["Expertise"],
      7: ["Evasion"],
      9: ["Archetype Feature"],
      11: ["Reliable Talent"],
      13: ["Archetype Feature"],
      14: ["Blindsense"],
      15: ["Slippery Mind"],
      17: ["Archetype Feature"],
      18: ["Elusive"],
      20: ["Stroke of Luck"]
    }
  },
  sorcerer: {
    label: "Sorcerer",
    hitDie: 6,
    asiLevels: [4, 8, 12, 16, 19],
    subclassLevel: 3,
    subclassLabel: "Sorcerous Origin",
    levels: {
      1: ["Spellcasting"],
      2: ["Font of Magic"],
      3: ["Sorcerous Origin", "Metamagic"],
      6: ["Origin Feature"],
      10: ["Metamagic"],
      14: ["Origin Feature"],
      17: ["Metamagic"],
      18: ["Origin Feature"],
      20: ["Sorcerous Restoration"]
    }
  },
  warlock: {
    label: "Warlock",
    hitDie: 8,
    asiLevels: [4, 8, 12, 16, 19],
    subclassLevel: 3,
    subclassLabel: "Otherworldly Patron",
    levels: {
      1: ["Pact Magic"],
      2: ["Eldritch Invocations"],
      3: ["Otherworldly Patron", "Pact Boon"],
      6: ["Patron Feature"],
      10: ["Patron Feature"],
      11: ["Mystic Arcanum"],
      13: ["Mystic Arcanum"],
      15: ["Mystic Arcanum"],
      17: ["Mystic Arcanum"],
      20: ["Eldritch Master"]
    }
  },
  wizard: {
    label: "Wizard",
    hitDie: 6,
    asiLevels: [4, 8, 12, 16, 19],
    subclassLevel: 2,
    subclassLabel: "Arcane Tradition",
    levels: {
      1: ["Spellcasting", "Arcane Recovery"],
      2: ["Arcane Tradition"],
      6: ["Tradition Feature"],
      10: ["Tradition Feature"],
      14: ["Tradition Feature"],
      18: ["Spell Mastery"],
      20: ["Signature Spells"]
    }
  }
};
